// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qszxzcroqjucylhyrygb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzenh6Y3JvcWp1Y3lsaHlyeWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjkzMTIsImV4cCI6MjA3MjI0NTMxMn0._VWejOxA43cp1jiXgXRF_ufNF6vTS40FaTbeMH9H1kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});